// Code generated by "stringer -type=LF_Type"; DO NOT EDIT

package log

import "fmt"

const (
	_LF_Type_name_0 = "LdateLtime"
	_LF_Type_name_1 = "Lmicroseconds"
	_LF_Type_name_2 = "Llongfile"
	_LF_Type_name_3 = "Lshortfile"
	_LF_Type_name_4 = "Lfunctionname"
	_LF_Type_name_5 = "Lprefix"
	_LF_Type_name_6 = "LUTC"
)

var (
	_LF_Type_index_0 = [...]uint8{0, 5, 10}
	_LF_Type_index_1 = [...]uint8{0, 13}
	_LF_Type_index_2 = [...]uint8{0, 9}
	_LF_Type_index_3 = [...]uint8{0, 10}
	_LF_Type_index_4 = [...]uint8{0, 13}
	_LF_Type_index_5 = [...]uint8{0, 7}
	_LF_Type_index_6 = [...]uint8{0, 4}
)

func (i LF_Type) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _LF_Type_name_0[_LF_Type_index_0[i]:_LF_Type_index_0[i+1]]
	case i == 4:
		return _LF_Type_name_1
	case i == 8:
		return _LF_Type_name_2
	case i == 16:
		return _LF_Type_name_3
	case i == 32:
		return _LF_Type_name_4
	case i == 64:
		return _LF_Type_name_5
	case i == 128:
		return _LF_Type_name_6
	default:
		return fmt.Sprintf("LF_Type(%d)", i)
	}
}
