// Code generated by "stringer -type=LL_Type"; DO NOT EDIT

package log

import "fmt"

const (
	_LL_Type_name_0 = "LL_FatalLL_Error"
	_LL_Type_name_1 = "LL_Warn"
	_LL_Type_name_2 = "LL_Debug"
	_LL_Type_name_3 = "LL_Info"
	_LL_Type_name_4 = "LL_END"
)

var (
	_LL_Type_index_0 = [...]uint8{0, 8, 16}
	_LL_Type_index_1 = [...]uint8{0, 7}
	_LL_Type_index_2 = [...]uint8{0, 8}
	_LL_Type_index_3 = [...]uint8{0, 7}
	_LL_Type_index_4 = [...]uint8{0, 6}
)

func (i LL_Type) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _LL_Type_name_0[_LL_Type_index_0[i]:_LL_Type_index_0[i+1]]
	case i == 4:
		return _LL_Type_name_1
	case i == 8:
		return _LL_Type_name_2
	case i == 16:
		return _LL_Type_name_3
	case i == 32:
		return _LL_Type_name_4
	default:
		return fmt.Sprintf("LL_Type(%d)", i)
	}
}
