// Code generated by "stringer -type LL_Type globalloglevels"; DO NOT EDIT.

package globalloglevels

import "strconv"

const _LL_Type_name = "LL_FatalLL_ErrorLL_WarnLL_TraceServiceLL_MonitorLL_DebugLL_AdminAuditLL_AnalysisLL_TraceUserLL_TraceClientLL_TraceAOLL_TraceAILL_TraceTaskLL_TraceSuspectLL_TraceRPCLL_END"

var _LL_Type_map = map[LL_Type]string{
	1:     _LL_Type_name[0:8],
	2:     _LL_Type_name[8:16],
	4:     _LL_Type_name[16:23],
	8:     _LL_Type_name[23:38],
	16:    _LL_Type_name[38:48],
	32:    _LL_Type_name[48:56],
	64:    _LL_Type_name[56:69],
	128:   _LL_Type_name[69:80],
	256:   _LL_Type_name[80:92],
	512:   _LL_Type_name[92:106],
	1024:  _LL_Type_name[106:116],
	2048:  _LL_Type_name[116:126],
	4096:  _LL_Type_name[126:138],
	8192:  _LL_Type_name[138:153],
	16384: _LL_Type_name[153:164],
	32768: _LL_Type_name[164:170],
}

func (i LL_Type) String() string {
	if str, ok := _LL_Type_map[i]; ok {
		return str
	}
	return "LL_Type(" + strconv.FormatInt(int64(i), 10) + ")"
}
